branches:
  only:
  - master
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
script:
- docker build . -t developmentsoftware/api-gateway