version: '2'

services:
    api-gateway:
        build: ./
        environment:
            MONGO_URI: "mongodb://mongo:27017/auth"
        volumes:
          - "./src:/src/app"
        ports:
          - "3000:3000"
          - "5858:5858"
    mongo:
        image: "mongo"
        volumes:
          - "~/.gamantech/data/mongo:/data/db"
        ports:
          - "27017:27017"
          - "8081:8081"