version: '2'

services:
    api-gateway:
        build: "./"
        environment:
            MONGO_URI: ${MONGO_URI}
            ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
            REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
            SECRET: ${APP_SECRET}
        volumes:
          - "./src:/src/app"
        ports:
         - "${PORT}:3000"
         - "5858:5858"
        expose:
         - "5858"
        command: yarn start
    mongo:
        image: "mongo"
        volumes:
          - "${DATA_DIR}/mongo:/data/db"
        ports:
          - "27017:27017"